name: Tester

on:
  workflow_dispatch:
  push:
    branches: 'master'
  schedule:
    - cron: '0 */12 * * *'

jobs:
  legacy:
    name: Legacy Test
    runs-on: windows-latest
    steps:
      - name: Checkout Workspace
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          path: hashcat
      - name: Initialize Validators
        uses: potatoqualitee/psmodulecache@v5.1
        with:
          modules-to-cache: BuildHelpers
          shell: powershell
      - name: Test Workspace
        shell: powershell
        run: |
          .\hashcat\binaries\test.ps1
  latest:
    name: Latest Test
    runs-on: windows-latest
    steps:
      - name: Checkout Workspace
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          path: hashcat
      - name: Initialize Validators
        uses: potatoqualitee/psmodulecache@v5.1
        with:
          modules-to-cache: BuildHelpers
          shell: pwsh
      - name: Test Workspace
        shell: pwsh
        run: |
          .\hashcat\binaries\test.ps1
